import fs from 'fs';
import path from 'path';
import { query } from '../db/postgres.js';
import { uploadDir } from '../config/upload.js';

const store = app => { if (!app.locals.mediaStore) app.locals.mediaStore = []; return app.locals.mediaStore; };
export async function getMedia(req,res){ try { if (!process.env.DATABASE_URL) return res.json(store(req.app)); const r=await query('SELECT * FROM adal_media ORDER BY uploaded_at DESC'); return res.json(r.rows); } catch(e){ return res.status(500).json({message:e.message}); } }
export async function uploadMedia(req,res){ try { if(!req.file)return res.status(400).json({message:'No image file provided.'}); const url=`/uploads/${req.file.filename}`; if(!process.env.DATABASE_URL){const x={id:Date.now(),image_url:url,image_name:req.file.originalname,mime_type:req.file.mimetype,size_bytes:req.file.size,uploaded_at:new Date().toISOString()};store(req.app).unshift(x);return res.status(201).json(x);} const r=await query('INSERT INTO adal_media (image_url,image_name,mime_type,size_bytes) VALUES ($1,$2,$3,$4) RETURNING *',[url,req.file.originalname,req.file.mimetype,req.file.size]);return res.status(201).json(r.rows[0]); }catch(e){return res.status(500).json({message:e.message});} }
export async function deleteMedia(req,res){ try { const id=Number(req.params.id); if(!process.env.DATABASE_URL){const a=store(req.app),i=a.findIndex(x=>Number(x.id)===id);if(i<0)return res.status(404).json({message:'Media not found.'});const url=a[i].image_url;a.splice(i,1);if(url){const f=path.join(uploadDir,path.basename(url));if(fs.existsSync(f))fs.unlinkSync(f);}return res.json({success:true});} const r=await query('DELETE FROM adal_media WHERE id=$1 RETURNING image_url',[id]);if(!r.rows.length)return res.status(404).json({message:'Media not found.'});const f=path.join(uploadDir,path.basename(r.rows[0].image_url||''));if(fs.existsSync(f))fs.unlinkSync(f);return res.json({success:true}); }catch(e){return res.status(500).json({message:e.message});} }
