import React, { useEffect, useRef, useState } from 'react';
import { Menu, X, MapPin, ChevronDown, House, Flame, Wrench, ShieldCheck, Newspaper, Phone, Users } from 'lucide-react';
import { AdalLogo } from './AdalLogo';
interface NavbarProps { onNavigate: (sectionId: string) => void; }
interface NavItem { label: string; target: string; icon: React.ElementType; }
export const Navbar: React.FC<NavbarProps> = ({ onNavigate }) => {
  const [isScrolled, setIsScrolled] = useState(false); const [mobileMenuOpen, setMobileMenuOpen] = useState(false); const [activeSection, setActiveSection] = useState('home');
  const navRef = useRef<HTMLElement | null>(null); const [indicator, setIndicator] = useState({ x: 0, width: 0 });
  const navLinks: NavItem[] = [
    { label: 'Home', target: 'home', icon: House }, { label: 'Cylinders & Prices', target: 'catalog', icon: Flame }, { label: 'Accessories', target: 'accessories', icon: Wrench }, { label: 'About Us', target: 'about', icon: Users }, { label: 'Why Adal', target: 'contact', icon: ShieldCheck }, { label: 'News & Updates', target: 'news', icon: Newspaper },
  ];
  const updateIndicator = (targetSection = activeSection) => { const active = navRef.current?.querySelector<HTMLElement>(`[data-nav-target="${targetSection}"]`); if (!active || !navRef.current) return; const parent = navRef.current.getBoundingClientRect(); const rect = active.getBoundingClientRect(); setIndicator({ x: rect.left - parent.left, width: rect.width }); };
  useEffect(() => { const handleScroll = () => setIsScrolled(window.scrollY > 20); const handleResize = () => updateIndicator(); window.addEventListener('scroll', handleScroll, { passive: true }); window.addEventListener('resize', handleResize); return () => { window.removeEventListener('scroll', handleScroll); window.removeEventListener('resize', handleResize); }; }, [activeSection]);
  useEffect(() => { const timer = window.setTimeout(() => updateIndicator(), 0); return () => window.clearTimeout(timer); }, [activeSection]);
  useEffect(() => { const sections = navLinks.map(link => document.getElementById(link.target)).filter((el): el is HTMLElement => Boolean(el)); if (!sections.length || !('IntersectionObserver' in window)) return; const observer = new IntersectionObserver(entries => { const visible = entries.filter(entry => entry.isIntersecting).sort((a,b) => b.intersectionRatio-a.intersectionRatio)[0]; if (visible) setActiveSection(visible.target.id); }, { rootMargin: '-18% 0px -65% 0px', threshold: [0.2,0.45,0.7] }); sections.forEach(section => observer.observe(section)); return () => observer.disconnect(); }, []);
  const handleLinkClick = (id: string) => { setMobileMenuOpen(false); setActiveSection(id); onNavigate(id); };
  return <>
    <div className="bg-slate-950 text-slate-200 text-xs py-2 px-4 border-b border-slate-800"><div className="max-w-7xl mx-auto flex items-center justify-center sm:justify-between gap-2"><span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-orange-500/15 text-orange-300 font-semibold border border-orange-500/20"><span className="w-1.5 h-1.5 rounded-full bg-orange-400 animate-pulse" /> Adal LPG Supply & Service</span><span className="hidden sm:flex items-center gap-1.5 text-slate-400"><MapPin className="w-3.5 h-3.5 text-cyan-400" /> Mbarara City, Uganda</span></div></div>
    <header className={`sticky top-0 z-40 transition-all duration-300 ${isScrolled ? 'bg-white/92 backdrop-blur-xl shadow-md border-b border-slate-200 py-2.5' : 'bg-white/85 backdrop-blur-lg border-b border-slate-100 py-3.5'}`}><div className="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8 flex items-center justify-between gap-3"><button onClick={() => handleLinkClick('home')} className="shrink-0 cursor-pointer select-none hover:opacity-90 transition-opacity" aria-label="Adal Energies home"><AdalLogo variant="horizontal" size="md" /></button>
      <nav ref={navRef} className="hidden lg:flex relative items-center gap-0.5 p-1.5 rounded-full bg-slate-100/80 border border-slate-200/80" aria-label="Primary navigation"><svg className="absolute inset-0 w-full h-full pointer-events-none overflow-visible" aria-hidden="true"><defs><filter id="adal-gooey-nav" x="-30%" y="-100%" width="160%" height="300%" colorInterpolationFilters="sRGB"><feGaussianBlur in="SourceGraphic" stdDeviation="5" result="blur" /><feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0.35 0 0 0 0.25  0 0 0 0 0  0 0 0 24 -10" result="goo" /><feGaussianBlur in="goo" stdDeviation="1.2" /></filter></defs><rect x={indicator.x} y="5" width={indicator.width} height="calc(100% - 10px)" rx="999" fill="#f97316" filter="url(#adal-gooey-nav)" className="liquid-indicator" /></svg>{navLinks.map(({label,target,icon:Icon}) => { const active=activeSection===target; return <button key={target} data-nav-target={target} onMouseEnter={() => updateIndicator(target)} onMouseLeave={() => updateIndicator(activeSection)} onClick={() => handleLinkClick(target)} className={`relative z-10 flex items-center gap-1 whitespace-nowrap rounded-full px-2.5 py-2.5 text-[11px] xl:text-[12px] font-bold transition-colors duration-200 ${active?'text-white':'text-slate-700 hover:text-orange-700'}`} aria-current={active?'page':undefined}><Icon className="w-3.5 h-3.5"/><span>{label}</span></button>; })}<div className="relative z-20 group"><button data-nav-target="news" className="relative z-10 flex items-center gap-1 whitespace-nowrap rounded-full px-2.5 py-2.5 text-[11px] xl:text-[12px] font-bold text-slate-700 hover:text-orange-700" onClick={()=>handleLinkClick('news')}><Newspaper className="w-3.5 h-3.5"/><span>News & Updates</span><ChevronDown className="w-3 h-3"/></button><div className="absolute right-0 top-full hidden pt-2 group-hover:block"><div className="w-48 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><button onClick={()=>handleLinkClick('news')} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-slate-700 hover:bg-orange-50 hover:text-orange-700">News & Updates</button><button onClick={()=>handleLinkClick('safety-guide')} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-slate-700 hover:bg-orange-50 hover:text-orange-700">Safety Guide</button><button onClick={()=>handleLinkClick('partners')} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-slate-700 hover:bg-orange-50 hover:text-orange-700">Partners</button></div></div></div></nav>
      <div className="flex items-center gap-2 shrink-0"><button onClick={() => handleLinkClick('contact-form')} className="hidden lg:inline-flex items-center gap-2 px-3 xl:px-4 py-2.5 rounded-xl text-sm font-bold text-white bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600 shadow-md shadow-orange-500/20 transition-all">Contact Depot</button><button onClick={() => setMobileMenuOpen(value=>!value)} className="lg:hidden p-2.5 rounded-xl text-slate-700 hover:bg-slate-100 border border-slate-200" aria-label="Toggle navigation menu" aria-expanded={mobileMenuOpen}>{mobileMenuOpen?<X className="w-5 h-5"/>:<Menu className="w-5 h-5"/>}</button></div></div>
      {mobileMenuOpen && <div className="lg:hidden mt-3 border-t border-slate-200 bg-white/98 backdrop-blur-xl px-3 sm:px-6 pt-3 pb-5 shadow-xl"><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{navLinks.map(({label,target,icon:Icon})=>{const active=activeSection===target;return <button key={target} onClick={()=>handleLinkClick(target)} className={`flex items-center gap-3 text-left px-4 py-3.5 rounded-2xl border transition-all ${active?'bg-orange-500 text-white border-orange-500 shadow-md':'bg-slate-50 text-slate-800 border-slate-200 hover:border-orange-200 hover:bg-orange-50'}`}><Icon className="w-5 h-5 shrink-0"/><span className="font-bold text-sm">{label}</span><ChevronDown className="ml-auto w-4 h-4 -rotate-90 opacity-60"/></button>;})}<div className="sm:col-span-2 rounded-2xl border border-slate-200 bg-slate-50 p-2"><div className="px-3 py-2 text-xs font-black uppercase tracking-wider text-slate-500">News & Updates</div><div className="grid grid-cols-1 sm:grid-cols-3 gap-1"><button onClick={()=>handleLinkClick('news')} className="rounded-xl px-3 py-2.5 text-left text-sm font-bold text-slate-700 hover:bg-white hover:text-orange-700">News & Updates</button><button onClick={()=>handleLinkClick('safety-guide')} className="rounded-xl px-3 py-2.5 text-left text-sm font-bold text-slate-700 hover:bg-white hover:text-orange-700">Safety Guide</button><button onClick={()=>handleLinkClick('partners')} className="rounded-xl px-3 py-2.5 text-left text-sm font-bold text-slate-700 hover:bg-white hover:text-orange-700">Partners</button></div></div><button onClick={()=>handleLinkClick('contact-form')} className="flex items-center gap-3 text-left px-4 py-3.5 rounded-2xl bg-slate-900 text-white sm:col-span-2"><Phone className="w-5 h-5 text-orange-400"/><span className="font-bold text-sm">Contact Depot</span></button></div><div className="mt-3 text-center text-xs text-slate-400">Tap a section to jump directly to it.</div></div>}
    </header>
  </>;
};
